# Generated by Django 3.2.5 on 2021-10-10 21:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('interval', models.CharField(choices=[('1m', '1 minute'), ('2m', '2 minute'), ('5m', '5 minute'), ('15m', '15 minute'), ('30m', '30 minute'), ('60m', '60 minute'), ('90m', '90 minute'), ('1h', '1 hour'), ('1d', '1 day'), ('5d', '5 day'), ('1wk', '1 week'), ('1mo', '1 month'), ('3mo', '3 month')], max_length=200)),
                ('period', models.CharField(choices=[('1d', '1 day'), ('5d', '5 day'), ('1mo', '1 month'), ('3mo', '3 month'), ('6mo', '6 month'), ('1y', '1 year'), ('2y', '2 year'), ('5y', '5 year'), ('10y', '10 year'), ('ytd', 'year-to-date'), ('max', 'Max')], max_length=200)),
                ('type', models.CharField(choices=[('candlestick', 'Candlestick'), ('ohlc', 'OHLC')], max_length=200)),
                ('rsi', models.BooleanField(default=False)),
                ('macd', models.BooleanField(default=False)),
            ],
        ),
    ]
